global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Exemple : ton app FastAPI exposant /metrics
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['host.docker.internal:8000']  # adapte selon ta VM ou config réseau
