name: Deploy Docker App via SSH

on:
  workflow_dispatch:

jobs:
  deploy-vm:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get VM IP
        id: get_ip
        run: echo "VM_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

      - name: Generate SSH key
        run: |
          ssh-keygen -t rsa -b 4096 -f temp-ssh-key -N ""
          echo "SSH_PRIVATE_KEY<<EOF" >> $GITHUB_ENV
          cat temp-ssh-key >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "SSH_PUBLIC_KEY=$(cat temp-ssh-key.pub)" >> $GITHUB_ENV

      - name: Save private key to file
        run: |
          echo "${{ env.SSH_PRIVATE_KEY }}" > temp-ssh-key.pem
          chmod 600 temp-ssh-key.pem

      - name: Deploy Docker container via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.VM_IP }}
          username: ubuntu
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            sudo apt-get update -y
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo docker pull nginx:latest
            sudo docker stop my-nginx || true
            sudo docker rm my-nginx || true
            sudo docker run -d --name my-nginx -p 80:80 nginx:latest
